add bulk workflow creation

diff --git a/shell/sg-cli b/shell/sg-cli
--- a/shell/sg-cli
+++ b/shell/sg-cli
@@ -112,6 +112,9 @@ Examples:
   # Create new workflow
   ./$(basename "$0") workflow create --org demo-org --workflow-group demo-wfgrp --workflow-id demo-wf -- payload.json
 
+  # Bulk create new workflows
+  ./$(basename "$0") workflow create --org demo-org --workflow-group demo-wfgrp -- payload.json
+
   # Create new workflow and patch for example "Description"
   ./$(basename "$0") workflow create --org demo-org --workflow-group demo-wfgrp --workflow-id demo-wf --patch-payload '{"Description": "New workflow"}' -- payload.json
 
@@ -142,6 +145,9 @@ Options:
   --workflow-id '':
     The workflow id in the workflow group.
 
+  --bulk:
+    Bulk import multiple workflows from JSON payload. Upload state files if they exist.
+
   --preview:
     Preview payload content before applying. Execution will not pause.
 
@@ -155,7 +161,7 @@ Options:
     Output execution response as json to STDIN.
 
 Usage:
-  ./$(basename "$0") workflow <sub-command> --org org-name --workflow-group wfgrp-name [--workflow-id wf-id] [options] -- [payload]
+  ./$(basename "$0") workflow <sub-command> --org org-name --workflow-group wfgrp-name [--workflow-id wf-id] [--bulk] [options] -- [payload]
 
 Use "./$(basename "$0") options" for a list of global command-line options (appiles to all commands).
 EOF
@@ -231,20 +237,30 @@ spinner() {
 #######################################
 
 parse_response() {
-  # full_response="$response"
+  full_response="$response"
   status_code="$(echo "$response" | awk '/^HTTP/ {print $2}')"
   response="$(echo "$response" | sed -n '/^{.*/,$p' | tr '\n' ' ')"
 
-  if [ "$status_code" != "200" ] && [ "$status_code" != "201" ]; then
+  if [ -z "$status_code" ]; then
+    echo "Unknown status code. API call was probably successfull."
+    echo "${response}" | jq
+  elif [ "$status_code" != "200" ] && [ "$status_code" != "201" ]; then
+    echo
     echo "== $1 =="
     echo "URL: ${url}"
     [ -n "$status_code" ] && echo "Status code: ${status_code}"
     echo "Response: ${response}"
+    echo "========================"
+    echo
 
     # echo "$full_response"
-    exit 1
+    if [ "${bulk_create}" = "false" ]; then
+      exit 1
+    fi
+    return 1
   else
-    echo "${response}" | jq
+    # echo "${response}" | jq
+    return 0
   fi
 }
 
@@ -293,24 +309,6 @@ workflow_list_all_help() {
   ./$(basename "$0") workflow list_all --org <ORG_NAME> --workflow-group <WF_GROUP_NAME>
 
 EOF
-}
-
-parse_response() {
-  full_response="$response"
-  status_code="$(echo "$response" | awk '/^HTTP/ {print $2}')"
-  response="$(echo "$response" | grep -E '^{.*')"
-
-  if [ "$status_code" != "200" ] && [ "$status_code" != "201" ]; then
-    echo "== $1 =="
-    echo "URL: ${url}"
-    [ -n "$status_code" ] && echo "Status code: ${status_code}"
-    echo "Response: ${response}"
-
-    echo "$full_response"
-    exit 1
-  else
-    echo "${response}" | jq
-  fi
 }
 
 get_stack() {
@@ -638,62 +636,63 @@ outputs_stack() {
 #   if successfull/error.
 #######################################
 create_workflow() {
-  if [ -z "${org_id}" ] || [ -z "${wfgrp_id}" ] || [ -z "${payload}" ]; then
+  if [ -z "${org_id}" ] || [ -z "${payload}" ]; then
     echo
-    echo "ERROR: parameters --org, --workflow-group and payload are required"
+    echo "ERROR: parameters --org and payload are required"
     workflow_help
     exit 1
   fi
-  url="${api_url}/orgs/${org_id}/wfgrps/${wfgrp_id}/wfs/"
-  response=$(curl -i -s --http1.1 -X POST \
-    -H 'PrincipalId: ""' \
-    -H "Authorization: apikey ${api_token}" \
-    -H "Content-Type: application/json" \
-    --data-raw "${payload}" "${url}")
-  parse_response "Workflow creation failed"
-}
-bulk_create_workflow() {
-  if [ -z "${org_id}" ] || [ -z "${wfgrp_id}" ]; then
-    echo
-    echo "ERROR: parameters --org, --workflow-group are required"
-    workflow_create_help
-    exit 1
-  fi
-  url="${api_url}/orgs/${org_id}/wfgrps/${wfgrp_id}/wfs/"
-  # write a for loop to iterate over the list of workflows in payload
-  for workflow in "${payload[@]}"; do
-    # Perform desired actions on each workflow
-    echo "Processing workflow: $workflow"
-    # Add your code here to perform operations on each workflow
-    response=$(curl -s --http1.1 -X POST \
-    -H 'PrincipalId: ""' \
-    -H "Authorization: apikey ${api_token}" \
-    -H "Content-Type: application/json" \
-    --data-raw "${workflow}" "${url}")
-    if [ $? -eq 0 ] && echo "${response}" | grep -q -E "Workflow.*created"; then
-      if [ -z "${workflow[TfState]}" ]; then
-        echo "TfState is not provided for workflow: ${workflow[Name]}"
-        echo "Skipping the workflow"
+  if [ "${bulk_create}" = "true" ]; then
+    for workflow in $(echo "${payload}" | jq -c '.[]'); do
+      wf_id="$(echo "${workflow}" | jq -r '.ResourceName')"
+      wfgrp_id="$(echo "${workflow}" | jq -r '.CLIConfiguration.WorkflowGroup')"
+      url="${api_url}/orgs/${org_id}/wfgrps/${wfgrp_id}/wfs/"
+
+      echo
+      echo ">> Processing workflow: $wf_id"
+      response=$(curl -i -s --http1.1 -X POST \
+      -H 'PrincipalId: ""' \
+      -H "Authorization: apikey ${api_token}" \
+      -H "Content-Type: application/json" \
+      --data-raw "${workflow}" "${url}")
+      parse_response "Workflow creation failed"
+      [ $? -eq 0 ] && \
+        echo ">> Workflow created." && \
+        echo
+
+
+      tf_state_file_path="$(echo "${workflow}" | jq -r '.CLIConfiguration.TFStateFilePath')"
+      if [ -z "${tf_state_file_path}" ] || [ "${tf_state_file_path}" = "null" ]; then
+        echo "TfStateFilePath is not provided for workflow: $wf_id"
+        echo "Skipping update of state file.."
       else
-        echo "TfState is provided for workflow: ${workflow[Name]}"
-        echo "Updating the workflow"
-        url_for_getting_signed_url="${api_url}/orgs/${org_id}/wfgrps/${wfgrp_id}/wfs/${workflow[Name]}/tfstate_upload_url"
-        generate_signed_url=$(curl -s --http1.1 -X GET \
-                    -H 'PrincipalId: ""' \
-                    -H "Authorization: apikey ${api_token}" \
-                    -H "Content-Type: application/json" \
-                    "${url_for_getting_signed_url}")
-        signed_url=$generate_signed_url[msg]
-        echo "signed_url: $signed_url"
-        curl --upload-file "${workflow[TfState]}" "${signed_url}" -H "Content-Type: application/json"
+        echo "Updating the workflow..."
+        url_for_getting_signed_url="${api_url}/orgs/${org_id}/wfgrps/${wfgrp_id}/wfs/${wf_id}/tfstate_upload_url"
+        response=$(curl -i -s --http1.1 -X GET \
+        -H 'PrincipalId: ""' \
+        -H "Authorization: apikey ${api_token}" \
+        -H "Content-Type: application/json" \
+        "${url_for_getting_signed_url}")
+        parse_response "Unable to fetch signed url."
+        generate_signed_url="${response}"
+        signed_url="$(echo "${generate_signed_url}" | jq '.msg')"
+        echo "Uploading state file to Stackguardian.."
+        curl -X POST \
+          -H "Content-Type: application/json" \
+          -F "file=@${tf_state_file_path}" \
+          "${signed_url}"
+        echo "Upload completed."
+        echo
       fi
-      echo "${response}" | jq
-    else
-      echo "== Workflow creation failed =="
-      echo "url: ${url}"
-      echo "response: ${response}"
-    fi
-  done
+    done
+  else
+    response=$(curl -i -s --http1.1 -X POST \
+      -H 'PrincipalId: ""' \
+      -H "Authorization: apikey ${api_token}" \
+      -H "Content-Type: application/json" \
+      --data-raw "${payload}" "${url}")
+    parse_response "Workflow creation failed"
+  fi
 }
 
 #######################################
@@ -1240,7 +1239,7 @@ destroy_stack_parse_response() {
 #   if successfull/error.
 #######################################
 create_workflow_parse_response() {
-  if [ "${response}" != "" ]; then
+  if [ "${response}" != "" ] && [ -z "${bulk_create}" ]; then
     wf_id=${wf_id:-$(echo "${response}" | jq -r '.data.ResourceName')}
     # stack_run_id=$(echo "${response}" | jq -r '.data.stack.StackRunId')
     echo "${dashboard_url}/orgs/${org_id}/wfgrps/${wfgrp_id}/wfs/${wf_id}"
@@ -1525,7 +1524,7 @@ main() {
     echo "${payload}" | jq
   fi
 
-  response=$("${service_option}"_"${service}")
+  "${service_option}"_"${service}"
 
   if [ $? -ne 0 ]; then
     echo "${response}"
@@ -1658,6 +1657,10 @@ while [ $# -gt 0 ]; do
     --workflow-id)
       wf_id="$2"
       shift 2
+      ;;
+    --bulk)
+      readonly bulk_create=true
+      shift
       ;;
     --wait)
       readonly wait_execution=true
