fix stack runs

diff --git a/shell/sg-cli b/shell/sg-cli
--- a/shell/sg-cli
+++ b/shell/sg-cli
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# set -e
+
 # Define variables
 [ -f .env ] && . .env
 readonly base_url="${SG_BASE_URL:-"https://app.api.stackguardian.io/"}"
@@ -192,9 +194,9 @@ EOF
 }
 
 create_stack() {
-  if [ -z "${org_id}" ] || [ -z "${wfgrp_id}" ]; then
+  if [ -z "${org_id}" ] || [ -z "${wfgrp_id}" ] || [ -z "${payload}" ]; then
     echo
-    echo "ERROR: parameters --org, --workflow-group are required"
+    echo "ERROR: parameters --org, --workflow-group and payload are required"
     stack_create_help
     exit 1
   fi
@@ -205,7 +207,7 @@ create_stack() {
     -H "Authorization: apikey ${api_token}" \
     -H "Content-Type: application/json" \
     --data-raw "${payload}" "${url}")
-  if [ $? -eq 0 ] && echo "${response}" | grep -q -E "Stack.*created"; then
+  if [ $? -eq 0 ] && echo "${response}" | grep -q -E "Created.*stack.*"; then
     echo "${response}" | jq
   else
     echo "== Stack creation failed =="
@@ -719,7 +721,7 @@ apply_workflow_parse_response() {
   fi
 
   # check stackrun status
-  if [ "${wait_execution}" = "true" ]; then
+  if [ "${wait_execution}" = "true" ] && [ "${run_on_create}" = "true" ]; then
     echo "Workflow run executed"
     while [ "$(get_workflow_status)" != "ERRORED" ] \
       && [ "$(get_workflow_status)" != "COMPLETED" ] \
@@ -730,7 +732,7 @@ apply_workflow_parse_response() {
   fi
 
   # print final stack status
-  if [ "${wait_execution}" = "true" ]; then
+  if [ "${wait_execution}" = "true" ] && [ "${run_on_create}" = "true" ]; then
     echo "Workflow finished with $(get_workflow_status) status"
     exit 0
   else
@@ -749,7 +751,7 @@ apply_stack_parse_response() {
   fi
 
   # check stackrun status
-  if [ "${wait_execution}" = "true" ]; then
+  if [ "${wait_execution}" = "true" ] && [ "${run_on_create}" = "true" ]; then
     echo "Stack run executed"
     while [ "$(get_stackrun_status)" != "ERRORED" ] \
       && [ "$(get_stackrun_status)" != "COMPLETED" ] \
