tested changed to accept inline json payload

diff --git a/sg-cli b/sg-cli
--- a/sg-cli
+++ b/sg-cli
@@ -2060,21 +2060,25 @@ while [ $# -gt 0 ]; do
         err "Only file name should be provided after --"
         exit 1
       fi
-      if [ -e "$1" ]; then
-        if [ -f "$1" ]; then
-          if jq '.' "$1" >/dev/null 2>&1; then
-            payload="$(cat "$1")"
+     if jq '.' <<< "$1" >/dev/null 2>&1; then
+      payload="$1"
+     else
+        if [ -e "$1" ]; then
+          if [ -f "$1" ]; then
+            if jq '.' "$1" >/dev/null 2>&1; then
+              payload="$(cat "$1")"
+            else
+              err "Invalid JSON format in file '$1'."
+              exit 1
+            fi
           else
-            err "Invalid JSON format."
+            err "'$1' is not recognized as file"
             exit 1
           fi
         else
-          err "'$1' is not recognized as file"
-          exit 1
+            err "File '$1' not found or does not exist"
+            exit 1
         fi
-      else
-        err "file $1 not found or does not exist"
-        exit 1
       fi
       break
       ;;
